global:
  scrape_interval: 5s
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'arxiv-api'
    static_configs:
      - targets: ['arxiv-api:8000']
 
  - job_name: 'arxiv-scraper'
    static_configs:
      - targets: ['arxiv-scraper:8001']